import Head from 'next/head'
import Navbar from '../components/Navbar'
import Welcome from '../components/Welcome'
import Services from '../components/Services'
import About from '../components/About'
import Team from '../components/Team'
import Contact from '../components/Contact'
import CTA from '../components/CTA'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Atrialogics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main className='overflow-x-hidden'>
        <header>
          <Navbar />
          <div className='py-[50px]'></div>
        </header>
        <main className='lg:max-w-screen-xl md:max-w-screen-md mx-auto'>
          <Welcome />
          <Services />
          <About />
          <Team />
          <Contact />
          <CTA />
        </main>
        <footer className='w-full'>
          <Footer />
        </footer>
      </main>
    </>
  )
}
