import { client } from '../../../lib/apollo'
import { gql } from '@apollo/client'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import BlogPage from '../../components/BlogPage'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'

import AOS from 'aos';
import 'aos/dist/aos.css';
interface Props {
    post: any;
}

export default function Blogs({ post }: Props): JSX.Element {

    useEffect(() => {
        AOS.init();
      }, [])

    // Adding id attribute to all the h tags in the content
    let sectionIndex = 0;
    const processedContent = post.content?.replace(/<(h[1-6])/g, (match: any, p1: any) => {
        sectionIndex++;
        return `<${p1} id="section${sectionIndex}" class="before:block before:h-[100px] before:-mt-[100px]"`;
    });

    // To determine how long it will take to read the post. General speed is 200 words per minute. Change 200 to something else to change the rate.
    const minRead = (content: string) => {
        const words = content.split(' ')
        const minutesToRead = Math.ceil(words.length / 200);
        return minutesToRead
    }
  
    // Creating an array of headings from the content, so we can display them in the sidebar
    const [headings, setHeadings] = useState<Element[]>([]);
    useEffect(() => {
        const content = processedContent;
        const parser = new DOMParser();
        const parsedContent = parser.parseFromString(content, "text/html");
        const headings = parsedContent.querySelectorAll("h1, h2, h3, h4, h5, h6");
        setHeadings(Array.from(headings));
    }, [processedContent]);

    // Tried to push the /blogs url as we press the browser back button (because when user press headings to scroll to them, that adds #... to url which wasn't desired). Now I did that with a function. 
    // const router = useRouter();

    // const onPopState = (event: any) => {
    //     window.history.pushState({}, '', '/blogs');
    //     router.push('/blogs');
    //   };
      
    //   useEffect(() => {
    //     window.addEventListener('popstate', onPopState);
      
    //     return () => {
    //       window.removeEventListener('popstate', onPopState);
    //     };
    //   }, []);
    

    return (
        <>
            <Head>
                <title>{post.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link href="https://fonts.googleapis.com/css2?family=Lexend+Giga:wght@200;300;400;500;600;700;800;900&display=swap"rel="stylesheet"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='overflow-x-hidden'>
                <header>
                <Navbar />
                <div className='py-[50px]'></div>
                </header>
                <main className='max-w-screen-xl mx-auto'>
                    <div className='flex flex-col justify-between items-start px-8 pb-16 space-y-16'>
                        {post.featuredImage ? <Image data-aos='fade-up' className='rounded-3xl self-center h-[80vh]' src={post.featuredImage.node.sourceUrl} width={800} height={500} alt='' /> : <Image data-aos='fade-up' src='/assets/ecommerce.svg' className='rounded-3xl self-center h-[80vh]' alt='' width={800} height={500} /> }
                        <h1 data-aos='fade-up' className='text-4xl font-bold w-full text-left'>{post.title}</h1>
                        <div className='flex justify-start items-center space-x-16'>
                            <h3 className='text-lg font-medium'>{post.author.node.name}</h3>
                            {post.content && <p>{`${minRead(processedContent)} min read`}</p>}
                        </div>
                        <BlogPage headings={headings} processedContent={processedContent} />
                        <Link href='/blogs'>&larr; Back to Blog</Link>
                    </div>
                </main>
                <footer className='w-full'>
                    <Footer />
                </footer>
            </main>
        </>
    )
}

export async function getStaticPaths() {
    const result = await client.query({
        query: gql`
            query GetPosts {
                posts {
                    nodes {
                        slug
                    }
                }
            }
        `
    })

    return {
        paths: result.data.posts.nodes.map(({ slug }: any) => {
            return {
                params: { slug }
            }
        }),
        fallback: false
    }
}

export async function getStaticProps({ params }: any) {
    const { slug } = params;
    const result = await client.query({
        query: gql`
            query GetPostDataBySlug($slug: String!) {
                postBy(slug: $slug) {
                    title
                    content
                    date
                    slug
                    featuredImage {
                        node {
                            sourceUrl
                        
                        }
                    }
                    author {
                        node {
                          name
                        }
                    }
                }
            }
        `,
        variables: { slug }
    })

    return {
        props: {
            post: result.data.postBy
        }
    }
}